//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES5.Script.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ES5.Script.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambigious overloaded method {0} with {1} parameters.
        /// </summary>
        internal static string Ambigious_overloaded_method_0_with_1_parameters {
            get {
                return ResourceManager.GetString("Ambigious_overloaded_method_0_with_1_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine already running.
        /// </summary>
        internal static string eAlreadyRunning {
            get {
                return ResourceManager.GetString("eAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;begin&quot; expected.
        /// </summary>
        internal static string eBeginExpected {
            get {
                return ResourceManager.GetString("eBeginExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign a value to this expression.
        /// </summary>
        internal static string eCannotAssignValueToExpression {
            get {
                return ResourceManager.GetString("eCannotAssignValueToExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot break here.
        /// </summary>
        internal static string eCannotBreakHere {
            get {
                return ResourceManager.GetString("eCannotBreakHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot continue here.
        /// </summary>
        internal static string eCannotContinueHere {
            get {
                return ResourceManager.GetString("eCannotContinueHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot return here.
        /// </summary>
        internal static string eCannotReturnHere {
            get {
                return ResourceManager.GetString("eCannotReturnHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;catch&quot; or &quot;finally&quot; expected.
        /// </summary>
        internal static string eCatchOrFinallyExpected {
            get {
                return ResourceManager.GetString("eCatchOrFinallyExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing brace expected.
        /// </summary>
        internal static string eClosingBraceExpected {
            get {
                return ResourceManager.GetString("eClosingBraceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing bracket expected.
        /// </summary>
        internal static string eClosingBracketExpected {
            get {
                return ResourceManager.GetString("eClosingBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing parenthesis expected.
        /// </summary>
        internal static string eClosingParenthesisExpected {
            get {
                return ResourceManager.GetString("eClosingParenthesisExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon expected.
        /// </summary>
        internal static string eColonExpected {
            get {
                return ResourceManager.GetString("eColonExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file in comment.
        /// </summary>
        internal static string eCommentError {
            get {
                return ResourceManager.GetString("eCommentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;do&quot; expected.
        /// </summary>
        internal static string eDoExpected {
            get {
                return ResourceManager.GetString("eDoExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot expected.
        /// </summary>
        internal static string eDotExpected {
            get {
                return ResourceManager.GetString("eDotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate identifier &quot;{0}&quot;.
        /// </summary>
        internal static string eDuplicateIdentifier {
            get {
                return ResourceManager.GetString("eDuplicateIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate label: &quot;{0}&quot;.
        /// </summary>
        internal static string eDuplicateLabel {
            get {
                return ResourceManager.GetString("eDuplicateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;end&quot; expected.
        /// </summary>
        internal static string eEndExpected {
            get {
                return ResourceManager.GetString("eEndExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file in regular expression.
        /// </summary>
        internal static string eEOFInRegex {
            get {
                return ResourceManager.GetString("eEOFInRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file in string.
        /// </summary>
        internal static string eEOFInString {
            get {
                return ResourceManager.GetString("eEOFInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal expected.
        /// </summary>
        internal static string eEqualExpected {
            get {
                return ResourceManager.GetString("eEqualExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in character sequence.
        /// </summary>
        internal static string eErrorInCharacter {
            get {
                return ResourceManager.GetString("eErrorInCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error while compiling.
        /// </summary>
        internal static string eFatalErrorWhileCompiling {
            get {
                return ResourceManager.GetString("eFatalErrorWhileCompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;finally&quot; or &quot;except&quot; expected.
        /// </summary>
        internal static string eFinallyExceptExpected {
            get {
                return ResourceManager.GetString("eFinallyExceptExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier expected.
        /// </summary>
        internal static string eIdentifierExpected {
            get {
                return ResourceManager.GetString("eIdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;implementation&quot; expected.
        /// </summary>
        internal static string eImplementationExpected {
            get {
                return ResourceManager.GetString("eImplementationExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;interface&quot; expected.
        /// </summary>
        internal static string eInterfaceExpected {
            get {
                return ResourceManager.GetString("eInterfaceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: {0}.
        /// </summary>
        internal static string eInternalError {
            get {
                return ResourceManager.GetString("eInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence.
        /// </summary>
        internal static string eInvalidEscapeSequence {
            get {
                return ResourceManager.GetString("eInvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such function: {0}.
        /// </summary>
        internal static string eNoSuchFunction {
            get {
                return ResourceManager.GetString("eNoSuchFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot invoke non-function object.
        /// </summary>
        internal static string eNotAFunction {
            get {
                return ResourceManager.GetString("eNotAFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;of&quot; expected.
        /// </summary>
        internal static string eOfExpected {
            get {
                return ResourceManager.GetString("eOfExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one default case allowed in a switch statement.
        /// </summary>
        internal static string eOnlyOneDefaultAllowed {
            get {
                return ResourceManager.GetString("eOnlyOneDefaultAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one variable allowed in variable definition.
        /// </summary>
        internal static string eOnlyOneVariableAllowed {
            get {
                return ResourceManager.GetString("eOnlyOneVariableAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening brace expected.
        /// </summary>
        internal static string eOpeningBraceExpected {
            get {
                return ResourceManager.GetString("eOpeningBraceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening parenthesis expected.
        /// </summary>
        internal static string eOpeningParenthesisExpected {
            get {
                return ResourceManager.GetString("eOpeningParenthesisExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to runInThread cannot be modified when the script is running.
        /// </summary>
        internal static string eRunInThreadCannotBeModifiedWhenScriptIsRunning {
            get {
                return ResourceManager.GetString("eRunInThreadCannotBeModifiedWhenScriptIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not defined.
        /// </summary>
        internal static string eRuntimeUncaughtReference {
            get {
                return ResourceManager.GetString("eRuntimeUncaughtReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolon expected.
        /// </summary>
        internal static string eSemicolonExpected {
            get {
                return ResourceManager.GetString("eSemicolonExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error.
        /// </summary>
        internal static string eSyntaxError {
            get {
                return ResourceManager.GetString("eSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;then&quot; expected.
        /// </summary>
        internal static string eThenExpected {
            get {
                return ResourceManager.GetString("eThenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;to&quot; or &quot;downto&quot; expected.
        /// </summary>
        internal static string eToDowntoExpected {
            get {
                return ResourceManager.GetString("eToDowntoExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file.
        /// </summary>
        internal static string eUnexpectedEndOfFile {
            get {
                return ResourceManager.GetString("eUnexpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown character.
        /// </summary>
        internal static string eUnknownCharacter {
            get {
                return ResourceManager.GetString("eUnknownCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown label target: &quot;{0}&quot;.
        /// </summary>
        internal static string eUnknownLabelTarget {
            get {
                return ResourceManager.GetString("eUnknownLabelTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;until&quot; expected.
        /// </summary>
        internal static string eUntilExpected {
            get {
                return ResourceManager.GetString("eUntilExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;while&quot; keyword expected.
        /// </summary>
        internal static string eWhileExpected {
            get {
                return ResourceManager.GetString("eWhileExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with statements are not allowed in a strict context.
        /// </summary>
        internal static string eWithNotAllowedInStrict {
            get {
                return ResourceManager.GetString("eWithNotAllowedInStrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No overloaded method {0} with {1} parameters.
        /// </summary>
        internal static string No_overloaded_method_0_with_1_parameters {
            get {
                return ResourceManager.GetString("No_overloaded_method_0_with_1_parameters", resourceCulture);
            }
        }
    }
}
